### ISSUE TITLE
MutableArray in Buffer is not UNPACKed

### ISSUE THREAD

**Issue by meooow25** [konsumlamm/rrb-vector#13]
https://github.com/konsumlamm/rrb-vector/blob/204a6437c6fa170429555cc7bf524b3d3d916cb5/src/Data/RRBVector/Internal/Buffer.hs#L19-L20

Unpacking the `MutableArray` would likely give a small performance benefit. Or better, `Buffer` could use a `SmallMutableArray` directly since it does not need to support slicing.

**Comment by konsumlamm** [comment]
You're right, although looking at the core, `Buffer` seems to be always unpacked and the `start` & `length` fields are optimized away. Feel free to open a PR anyway!

**Comment by meooow25** [comment]
Nice, I hadn't checked the core.
I'll make a PR 👍
