### ISSUE TITLE
Question: Why sliceable arrays?

### ISSUE THREAD

**Issue by meooow25** [konsumlamm/rrb-vector#14]
Why are the arrays stored in the RRB-tree nodes O(1)-sliceable?
It adds a memory cost of 2 words per node, but the benefit is not clear to me from looking through the code.
The original paper describing the tree and its Scala implementation use regular fixed-length arrays, so reading that didn't shed light on it either.

**Comment by konsumlamm** [comment]
The O(1) slicing is so that we don't have to do unnecessary copies in `><`, `take`, `drop` and `splitAt`. I think I remember seeing a speedup for those, but I'll have to benchmark again and document if O(1) slicing is worth it.

**Comment by konsumlamm** [comment]
I did some benchmarks and `take` and `drop` noticeably benefit from O(1) slicing, while the others stay largely the same.

**Comment by meooow25** [comment]
Thanks for checking. I was also planning to test it out and benchmark, but not sure when I'll get around to it. I'll update in the unlikely case that I see anything different.
