### ISSUE TITLE
Add value-strict interface

### ISSUE THREAD

**Issue by TeofilC** [konsumlamm/rrb-vector#7]
I would find a value-strict interface to this data structure helpful.

The proposal is to add a new module called `Data.RRBVector.Strict` which exports a newtype wrapper around the existing type, and functions and typeclass instances that are all value-strict.

If this sounds OK I'd be happy to prepare a PR.

**Comment by konsumlamm** [comment]
The reason I didn't add a `Data.RRBVector.Strict` module originally is that I didn't want to duplicate the surface API. Doing that means having to write a bunch of wrapper boilerplate and duplicating the doc comments (and keeping them in sync!), which I think isn't worth it. Fwiw, similar modules like [`Data.Sequence`](https://hackage.haskell.org/package/containers/docs/Data-Sequence.html) and [`Data.Vector`](https://hackage.haskell.org/package/vector/docs/Data-Vector.html) don't expose a strict version either (yes, I know about `Data.Vector.Unboxed`, but that uses a different representation altogether), the default in Haskell is lazy after all.

As a workaround, you can always manually make sure that the values are evaluated before putting them in a `Vector`. `Data.RRBVector` also provides `adjust'` and `map'` (not yet released) as strict versions of `adjust` and `map`, respectively.

What do you think?

**Comment by TeofilC** [comment]
Thanks for explaining your perspective. I think it's quite reasonable not to want to take on that extra maintenance burden.

I don't think that those steps would be enough for me unfortunately. Preferably I would like to maintain strictness invariants via distinct types. I find trying to enforce strictness invariants by using strict versions of functions very error-prone, especially because typeclass instances make it very easy to accidentally use a non-strict version.

After thinking this over a bit more, I think the best thing is probably for me to fork this package and keep a strict version in sync with this one. Having it be out of tree probably makes it easier to keep things in sync and places the burden on people like me who would like to have this variant rather than on you.
